on: [push, pull_request]

name: CI for 'leanpub-...' libraries

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['8.8.3', '8.10.3']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '.github/workflows/haskell.hs') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: runhaskell --ghc-arg='-package process' ./.github/workflows/haskell.hs
        env:
          ghc: ${{ matrix.ghc }}
